# Generated by Django 4.2.23 on 2025-11-18 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Subject contains invalid characters', regex="^[a-zA-Z0-9\\s\\-\\_\\.\\,\\!\\?\\']+")]),
        ),
    ]
