# Generated by Django 3.2.25 on 2025-11-13 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20251107_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Subject contains invalid characters', regex="^[a-zA-Z0-9\\s\\-\\_\\.\\,\\!\\?\\']+")]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Message contains invalid characters', regex='^[^\\n\\r\\t\\f\\v]+$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
