# Generated by Django 3.2.25 on 2025-11-13 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20251113_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator(message='Message contains invalid characters', regex='^[^\\n\\r\\t\\f\\v]+$')]),
        ),
    ]
