# Generated by Django 3.2.25 on 2025-10-31 00:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20251030_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPG', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='products/'),
        ),
    ]
